### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by yp233** [DecaYale/VLocNet#3]
it  seems that the 'trainsplit.txt' was forgotten to push

**Comment by yp233** [comment]
I think the code should be unfinished?????

**Comment by yp233** [comment]
Hi, sorry to bother u. I found in trainer.py line 237 function "quaternion_angular_error" seems lack of input arguments.
![image](https://user-images.githubusercontent.com/30382622/56859096-9ec32980-69b8-11e9-95b8-1f7c402a6db1.png)

**Comment by DecaYale** [comment]
1. `trainsplit.txt' is provided by the 7Scenes dataset officially. Download them from the official website (https://www.microsoft.com/en-us/research/project/rgb-d-dataset-7-scenes/) and check it again. 
2. quaternion_angular_error is a function defined under the subfolder `utils'.  
I am a little busy these days. Instance response will not be guaranteed in the following weeks. Our project taking the project of MapNet as a reference (https://github.com/NVlabs/geomapnet) is merely for experimental purposes.  It is strongly recommended you proactively modify the code and adapt it to your own project.

**Comment by yp233** [comment]
@DecaYale OK! Thanks a lot ！I will do it  by myself。
